name: Deploy Portfolio

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2a: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 2b: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 3a: HTML Validation
      - name: Validate HTML
        run: |
          sudo apt-get install tidy
          tidy -q -e **/*.html || true

      # Step 3b: CSS Validation
      - name: Validate CSS
        run: |
          npx stylelint "**/*.css" || true

      # Step 3c: JavaScript Linting
      - name: Lint JavaScript
        run: |
          npx eslint "**/*.js" || true

      # Step 4: Create automated PR for deployment
      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: deploy-changes
          base: main
          title: Deploy updates
          body: "This PR contains the latest updates for deployment."
          commit-message: "Deploy updates 🚀"

      # Step 5: Enable and trigger auto-merge
      - name: Enable Auto-merge
        if: steps.create-pr.outputs.pull-request-number
        run: |
          gh pr merge --auto --merge "${{ steps.create-pr.outputs.pull-request-number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"