name: Deploy Portfolio

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Validate HTML și CSS 
      - name: Validate HTML
        run: |
          sudo apt-get install tidy
          tidy -q -e **/*.html || true

      - name: Validate CSS
        run: |
          for file in $(find . -name "*.css"); do
            npx stylelint $file || true
          done

      # 3. Deploy to GitHub Pages 
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: .  
